#!/bin/bash
set -eu
shopt -s expand_aliases

TEST_POD_NAMESPACE="${TEST_POD_NAMESPACE:-kube-system}"
TEST_POD_IMAGE="${TEST_POD_IMAGE:-gcr.io/google_containers/pause:3.0}"
TEST_POD_NAME_POSTFIX="${TEST_POD_NAME_POSTFIX-'pod'}"
TEST_POD_NAME="scheduler-healthcheck-${TEST_POD_NAME_POSTFIX}"

cat > /tmp/pod.yaml <<endOfPodDef
apiVersion: v1
kind: Pod
metadata:
  name: ${TEST_POD_NAME}
  labels:
    app: scheduler-healthcheck-test-pod
spec:
  containers:
  - name: pause
    image: ${TEST_POD_IMAGE}
endOfPodDef

alias kubectl="timeout -t 30 kubectl --namespace \${TEST_POD_NAMESPACE}"
alias create-test-pod="kubectl create -f /tmp/pod.yaml"
alias get-test-pod="kubectl get pod \${TEST_POD_NAME}"
alias delete-test-pod="kubectl delete pod --selector='app=scheduler-healthcheck-test-pod' --grace-period=0"

trap delete-test-pod EXIT # cleanup before exit

delete-test-pod || true
sleep 1
delete-test-pod --force || true
create-test-pod
until [ "$(get-pod -o jsonpath='{.status.conditions[?(@.type == "PodScheduled")].status}')" == "True" ]; do
  get-test-pod
  get-test-pod -o jsonpath='{.status.conditions[?(@.type == "PodScheduled")].status}'
  sleep 1
done
delete-test-pod || true
sleep 1
delete-test-pod --force || true
