#!/bin/sh
set -eu
TEST_POD_NAMESPACE="${TEST_POD_NAMESPACE:-kube-system}"
TEST_POD_IMAGE="${TEST_POD_IMAGE:-gcr.io/google_containers/pause:3.0.0}"

cat > /tmp/pod.yaml <<endOfPodDef
apiVersion: v1
kind: Pod
metadata:
  name: scheduler-pod-healthcheck
spec:
  containers:
  - name: pause
    image: ${TEST_POD_IMAGE}
endOfPodDef

kubectl delete pod scheduler-pod-healthcheck -n $TEST_POD_NAMESPACE || true
kubectl create -f /tmp/pod.yaml -n $TEST_POD_NAMESPACE
until $(kubectl get pod scheduler-pod-healthcheck -n $TEST_POD_NAMESPACE -o jsonpath={.status.phase}) != 'Pending'; do sleep 1; done
kubectl delete pod scheduler-pod-healthcheck -n $TEST_POD_NAMESPACE
